baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Summer Fellowship 2024'
theme = 'hugo-texify2'
summaryLength = 30

[taxonomies]
	author = "authors"

[params]
title="Summer Fellowship 2024"
description = "Reflections on the summer fellowship 2024"
images = ['images/logo.jpg']
footnote = """witness and be witnessed"""
keywords = ["fellowship", "summmer", "paracademic", "blog"]
customCSS = ["css/custom.css"]
customJS = []
dateFormat = "January 2, 2006"
emphasisWithDots = true
since = "2024"
toc = true
showWordCount = false
showReadingTime = false
rootFontSize = "120%"
math = true
enableDuckDuckGoSearchBox = false
numberedSubtitles = false

[params.sharingButtons]
facebook = false
twitter = false
email = false
linkedin = false
reddit = false
whatsapp = false
hackernews = false
telegram = false

[[menu.main]]
identifier = "post"
name = "Posts"
url = "/"
weight = 1
[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 2
